// Generated by gencpp from file phasespace_msgs/Markers.msg
// DO NOT EDIT!


#ifndef PHASESPACE_MSGS_MESSAGE_MARKERS_H
#define PHASESPACE_MSGS_MESSAGE_MARKERS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <phasespace_msgs/Marker.h>

namespace phasespace_msgs
{
template <class ContainerAllocator>
struct Markers_
{
  typedef Markers_<ContainerAllocator> Type;

  Markers_()
    : header()
    , markers()  {
    }
  Markers_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , markers(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::phasespace_msgs::Marker_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::phasespace_msgs::Marker_<ContainerAllocator> >> _markers_type;
  _markers_type markers;





  typedef boost::shared_ptr< ::phasespace_msgs::Markers_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phasespace_msgs::Markers_<ContainerAllocator> const> ConstPtr;

}; // struct Markers_

typedef ::phasespace_msgs::Markers_<std::allocator<void> > Markers;

typedef boost::shared_ptr< ::phasespace_msgs::Markers > MarkersPtr;
typedef boost::shared_ptr< ::phasespace_msgs::Markers const> MarkersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phasespace_msgs::Markers_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phasespace_msgs::Markers_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::phasespace_msgs::Markers_<ContainerAllocator1> & lhs, const ::phasespace_msgs::Markers_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.markers == rhs.markers;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::phasespace_msgs::Markers_<ContainerAllocator1> & lhs, const ::phasespace_msgs::Markers_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace phasespace_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::phasespace_msgs::Markers_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phasespace_msgs::Markers_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phasespace_msgs::Markers_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phasespace_msgs::Markers_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phasespace_msgs::Markers_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phasespace_msgs::Markers_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phasespace_msgs::Markers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87fe27df7445224826bbc3363f7dd056";
  }

  static const char* value(const ::phasespace_msgs::Markers_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87fe27df74452248ULL;
  static const uint64_t static_value2 = 0x26bbc3363f7dd056ULL;
};

template<class ContainerAllocator>
struct DataType< ::phasespace_msgs::Markers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phasespace_msgs/Markers";
  }

  static const char* value(const ::phasespace_msgs::Markers_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phasespace_msgs::Markers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "########################################\n"
"# Messages\n"
"########################################\n"
"std_msgs/Header header\n"
"Marker[] markers\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: phasespace_msgs/Marker\n"
"########################################\n"
"# Messages\n"
"########################################\n"
"uint32 id\n"
"uint32 flags\n"
"uint64 time\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 cond\n"
;
  }

  static const char* value(const ::phasespace_msgs::Markers_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phasespace_msgs::Markers_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.markers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Markers_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phasespace_msgs::Markers_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phasespace_msgs::Markers_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "markers[]" << std::endl;
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      s << indent << "  markers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::phasespace_msgs::Marker_<ContainerAllocator> >::stream(s, indent + "    ", v.markers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHASESPACE_MSGS_MESSAGE_MARKERS_H
